---
abstract: 'Power sets of hashes'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
  - 'Mirela Iclodean <imirela@cpan.org>'
build_requires:
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::Deep::NoTest: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-PowerSet-Hash
requires:
  Data::PowerSet: 0
  Exporter: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/xsawyerx/data-powerset-hash
version: 0.04
